[package]
authors = [ "GF He <hgfkeep@outlook.com>" ]
edition = "2018"
name    = "std-demo"
version = "0.1.0"

[[bin]]
name = "main"
path = "src/bin/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
